url:
  home_page: "http://www.railstutorial.org/"
  news: "https://news.railstutorial.org"
  author: "https://www.michaelhartl.com"
  learn_enough: "https://www.learnenough.com"
  screen_casts: "https://screencasts.railstutorial.org"
  contact: "https://www.railstutorial.org/contact"
  book: "https://www.railstutorial.org/book"
  help: "https://www.railstutorial.org/help"
  gravatar_link: "https://gravatar.com/emails"
validate:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
page:
  size_avatar: 50
  total_element: 10
